# Especificar la imagen base de Node.js
FROM node:alpine

# Asignar un directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente de la aplicación al contenedor
COPY . .

# Exponer el puerto usado por la aplicación
EXPOSE 3000

# Comando por defecto para iniciar la aplicación dentro del contenedor
CMD ["npm", "start"]

